# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-25 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dom', models.CharField(max_length=200, verbose_name='заголовок')),
            ],
            options={
                'verbose_name': 'дом',
                'verbose_name_plural': 'дом',
            },
        ),
    ]
