# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180926_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paket',
            options={'verbose_name': 'пакет', 'verbose_name_plural': 'пакет'},
        ),
        migrations.AddField(
            model_name='paket',
            name='cena_paket',
            field=models.CharField(default=12, max_length=200, verbose_name='цена поката'),
            preserve_default=False,
        ),
    ]
