# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-27 07:41
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180926_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='dom',
            name='onas_predtext',
            field=models.CharField(blank=True, max_length=200, verbose_name='предтекст о нас'),
        ),
        migrations.AddField(
            model_name='dom',
            name='onas_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=12, verbose_name='текст о нас'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paket',
            name='paket_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='текст_пакета'),
        ),
        migrations.AlterField(
            model_name='usluga',
            name='usluga_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='текст_услуги'),
        ),
    ]
