# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-27 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180927_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podpaket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podpaket_title', models.CharField(max_length=200, verbose_name='название подпакета')),
            ],
            options={
                'verbose_name': 'подпакет',
                'verbose_name_plural': 'подпакет',
            },
        ),
        migrations.AlterField(
            model_name='paket',
            name='cena_paket',
            field=models.CharField(max_length=200, verbose_name='цена покета'),
        ),
        migrations.AddField(
            model_name='paket',
            name='podpaket_paket',
            field=models.ManyToManyField(to='polls.Podpaket', verbose_name='покет'),
        ),
    ]
