# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-27 10:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180927_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_title', models.CharField(max_length=200, verbose_name='контакт')),
                ('contact_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='текст_контакта')),
                ('email', models.CharField(max_length=200, verbose_name='контакт')),
                ('telefon', models.CharField(max_length=200, verbose_name='контакт')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакт',
            },
        ),
    ]
